local_costmap_font:
  plugins:
    - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
  global_frame: foot_print
  robot_base_frame: soma_link
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05
  update_frequency: 3.0
  publish_frequency: 3.0

  obstacle_layer:
    observation_sources: rgbd_l rgbd_r
    rgbd_l:
      sensor_frame: soma_link
      topic: camera_L/filtered_points
      # topic: camera_L/depth_registered/points
      data_type: PointCloud2
      marking: true
      clearing: true
      min_obstacle_height: 0.0
    rgbd_r:
      sensor_frame: soma_link
      topic: camera_R/filtered_points
      # topic: camera_R/depth_registered/points
      data_type: PointCloud2
      marking: true
      clearing: true
      min_obstacle_height: 0.0
      obstacle_range: 4.0

    # rgbd_b:
    #   sensor_frame: camera_B_link
    #   topic: camera_B/depth_registered/points
    #   data_type: PointCloud2
    #   marking: true
    #   clearing: true
