global_costmap:
  plugins:
   - {name: static_layer, type: "cotmap_2d:StaticLayer"}
  global_frame: map
  robot_base_frame: velodyne
  update_frequency: 2.0
  publish_frequency: 2.0
  static_layer:
    map_topic: /hdl_graph_slam/map_points
    track_unknown_space: false
    subscribe_to_updates: true