# base_local_planner:
  # acc_lim_x: 20.0
  # acc_lim_theta: 20.0
  # max_val_x: 1.2
  # min_val_x: 0.05
  # max_vel_theta: 20.0
  # min_vel_theta: -20.0
  # min_in_place_vel_theta: 0.4
  # max_rotational_vel: 0.5
  # holonomic_robot: false
  # meter_scoring: true
  # controller_frequency: 0.1
  # yaw_goal_tolerance: 0.1
  # xy_goal_tolerance: 0.15
  # sim_time: 5.0
  # sim_granularity: 0.5
  # angular_sim_granularity: 0.5
  # dwa: true
  # vx_samples: 20
  # vtheta_samples: 30
  # meter_scoring: false
  # pdist_scale: 0.1
  # gdist_scale: 0.2
  # occdist_scale: 0.6

dwa_local_planner:
  acc_lim_x: 2.5
  acc_lim_th: 5.0
  max_vel_x: 1.2
  min_vel_x: -1.2
  max_rot_val: 0.5 #rad/s
  min_rot_val: 0.0 #rad/s
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.10
  sim_time: 5.0
  sim_granularity: 0.02
  vx_samples: 30
  vth_samples: 30
  controller_frequency: 5.0
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01
  publish_cost_grid: true
  acc_lim_y: 0.0
