local_costmap:
  plugins: 
    - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
  global_frame: odom_dr
  robot_base_frame: soma_link
  # footprint: [[-0.2, -0.12], [-0.2, 0.12], [0.05, 0.12], [0.05, -0.12]]
  rolling_window: true
  width: 10
  height: 10
  resolution: 0.1
  update_frequency: 3.0
  publish_frequency: 3.0
  always_send_full_costmap: false
  max_obstacle_height: 5.0
  obstacle_range: 10
  conbination_method: 0

  # obstacle_layer:
  #   observation_sources: point_cloud_sensor
  #   point_cloud_sensor: 
  #     sensor_frame: camera_link
  #     topic: obstacle_points
  #     data_type: PointCloud2
  #     marking: true
  #     clearing: true

  obstacle_layer:
    observation_sources: point_cloud_sensor
    point_cloud_sensor: 
      sensor_frame: soma_link
      topic: ground
      data_type: PointCloud2
      marking: true
      clearing: true
      min_obstacle_height: -1

    # observation_sources: rgbd_l rgbd_r
    # rgbd_l:
    #   sensor_frame: soma_link
    #   topic: camera_L/filtered_points
    #   # topic: camera_L/depth_registered/points
    #   data_type: PointCloud2
    #   marking: true
    #   clearing: true
    #   min_obstacle_height: 0.0
    # rgbd_r:
    #   sensor_frame: soma_link
    #   topic: camera_R/filtered_points
    #   # topic: camera_R/depth_registered/points
    #   data_type: PointCloud2
    #   marking: true
    #   clearing: true
    #   min_obstacle_height: 0.0
    #   obstacle_range: 4.0